coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        informational: true

comment:
  layout: "reach,diff,flags"
  require_changes: false
